
# Dragon Spawn Config
[Stinger]
	# Dragon spawn Biomes and Values can be adjusted using this Config.
	# value 1: The spawn Weight, used for the given Biomes.
	# value 2: The Minimum Count to spawn.
	# value 3: The Maximum Count to spawn.
	# value 4: The Biomes to spawn in.
	# If there is a different desired value of weight/counts simply add a new list entry.
	#
	stinger_data = ["10 | 2 | 4 | minecraft:sunflower_plains, minecraft:savanna, minecraft:savanna_plateau", "2 | 0 | 2 | minecraft:badlands, minecraft:wooded_badlands, minecraft:eroded_badlands"]

["Terrible Terror"]
	# Usage described at the top.
	terrible_terror_data = ["1 | 0 | 3 | minecraft:stony_shore, minecraft:river, minecraft:beach", "4 | 2 | 4 | minecraft:jungle, minecraft:bamboo_jungle, minecraft:dark_forest"]

["Deadly Nadder"]
	# Usage described at the top.
	deadly_nadder_data = ["2 | 2 | 3 | minecraft:snowy_plains, minecraft:meadow", "4 | 2 | 3 | minecraft:windswept_hills, minecraft:windswept_gravelly_hills, minecraft:windswept_forest", "6 | 2 | 4 | minecraft:sparse_jungle, minecraft:savanna, minecraft:savanna_plateau", "9 | 1 | 3 | minecraft:grove, minecraft:forest, minecraft:flower_forest, minecraft:birch_forest, minecraft:old_growth_birch_forest, minecraft:windswept_savanna"]

[Gronckle]
	# Usage described at the top.
	gronckle_data = ["2 | 1 | 2 | minecraft:snowy_plains, minecraft:swamp, minecraft:meadow", "5 | 2 | 3 | minecraft:old_growth_birch_forest, minecraft:savanna_plateau, minecraft:windswept_savanna", "6 | 1 | 2 | minecraft:plains, minecraft:grove, minecraft:sunflower_plains, minecraft:savanna"]

["Hideous Zippleback"]
	# Usage described at the top.
	zippleback_data = ["6 | 2 | 3 | minecraft:sparse_jungle", "1 | 0 | 1 | minecraft:ice_spikes, minecraft:snowy_plains, minecraft:swamp"]

["Light Fury"]
	# Usage described at the top.
	light_fury_data = ["3 | 0 | 1 | minecraft:jagged_peaks, minecraft:frozen_peaks, minecraft:windswept_forest, minecraft:birch_forest, minecraft:old_growth_birch_forest"]

["Night Fury"]
	# Usage described at the top.
	night_fury_data = ["2 | 0 | 1 | minecraft:snowy_slopes, minecraft:jagged_peaks, minecraft:frozen_peaks, minecraft:windswept_hills, minecraft:windswept_gravelly_hills, minecraft:stony_peaks"]

["Monstrous Nightmare"]
	# Usage described at the top.
	nightmare_data = ["1 | 0 | 1 | minecraft:badlands, minecraft:wooded_badlands, minecraft:eroded_badlands", "1 | 0 | 1 | minecraft:windswept_hills, minecraft:windswept_gravelly_hills, minecraft:windswept_forest"]

[Skrill]
	# Usage described at the top.
	skrill_data = ["5 | 0 | 1 | minecraft:snowy_slopes, minecraft:jagged_peaks, minecraft:frozen_peaks, minecraft:stony_peaks"]

["Triple Stryke"]
	# Usage described at the top.
	triple_stryke_data = ["1 | 0 | 2 | minecraft:wooded_badlands, minecraft:badlands", "5 | 1 | 3 | minecraft:snowy_taiga, minecraft:taiga, minecraft:old_growth_pine_taiga, minecraft:old_growth_spruce_taiga"]

